#!/usr/bin/env python3

import argparse
import json
import yaml
import boto3

def main(argv=None):
    argp = argparse.ArgumentParser()
    argp.add_argument(
        '-n',
        '--name',
        required=True,
    )
    argp.add_argument(
        '-c',
        '--create',
        action='store_true'
    )
    argp.add_argument(
        '-d',
        '--definition',
        type=str,
    )
    argp.add_argument(
        '-D',
        '--delete',
        action='store_true'
    )

    args = argp.parse_args(argv)

    # -
    client = boto3.client('cloudformation', region_name='us-west-1')

    if args.delete:
        client.delete_stack(StackName=args.name)
        return 0

    with open(args.definition) as fp:
        data = yaml.load(fp)
        body = json.dumps(data)

    # -
    kwargs = {
        'StackName': args.name,
        'TemplateBody': body,
        'Capabilities': ['CAPABILITY_IAM'],
    }

    if args.create:
        client.create_stack(**kwargs)
    else:
        client.update_stack(**kwargs)

if __name__ == '__main__':
    main()
